### ISSUE TITLE
Are ProjectRef's to other, external SBT projects supported?

### ISSUE THREAD

**Issue by benhutchison** [dwijnand/sbt-project-graph#26]
I have a SBT project containing a scala.js Cross Project.

Both the JS and JVM sub-projects depend upon the JS/JVM parts of another (external) cross-project at a relative file path. They do this by creating `ProjectRef`s, eg `ProjectRef(file("../time", "TimeJVM")`.

What I observed when I generated & viewed the dot file was that these dependencies were missing.

**Comment by dwijnand** [comment]
Yeah when I wrote sbt-project-graph I didn't understand how sbt does multiple builds. See how I only use the current build:

https://github.com/dwijnand/sbt-project-graph/blob/v0.2.2/src/main/scala/sbtprojectgraph/SbtProjectGraphPlugin.scala#L18

This would be a great contribution.

**Comment by dwijnand** [comment]
Duplicate of #8
